export const Theme = {
    Dark: 'dark',
    Light: 'light',
};

export enum OtpType {
    REGISTER = 'register',
    PASSWORD = 'password',
}

export enum RoleType {
    AFFA = 'affa',
    CLUB = 'club',
}

export enum Permissions {
    club = 'club',
    clubs_view = 'clubs.view',
    clubs_add = 'clubs.add',
    clubs_edit = 'clubs.edit',
    clubs_namechange = 'clubs.namechange',
    clubs_history = 'clubs.history',
    clubs_delete = 'clubs.delete',
    associate = 'associate',
    associates_view = 'associates.view',
    associates_add = 'associates.add',
    associates_edit = 'associates.edit',
    associates_positionchange = 'associates.positionchange',
    associates_sendnotification = 'associates.sendnotification',
    associates_history = 'associates.history',
    associates_delete = 'associates.delete',
    document = 'document',
    documents_view = 'documents.view',
    documents_add = 'documents.add',
    documents_edit = 'documents.edit',
    documents_changestatus = 'documents.changestatus',
    documents_history = 'documents.history',
    documents_delete = 'documents.delete',
    questionnaire = 'questionnaire',
    questionnaires_view = 'questionnaires.view',
    questionnaires_add = 'questionnaires.add',
    questionnaires_edit = 'questionnaires.edit',
    questionnaires_delete = 'questionnaires.delete',
    announcement = 'announcement',
    announcements_view = 'announcements.view',
    announcements_add = 'announcements.add',
    announcements_edit = 'announcements.edit',
    announcements_sendnotification = 'announcements.sendnotification',
    announcements_viewall = 'announcements.viewall',
    announcements_deletecomment = 'announcements.deletecomment',
    announcements_changestatus = 'announcements.changestatus',
    announcements_delete = 'announcements.delete',
    role = 'role',
    roles_view = 'roles.view',
    roles_add = 'roles.add',
    roles_edit = 'roles.edit',
    roles_delete = 'roles.delete',
    meeting = 'meeting',
    meetings_view = 'meetings.view',
    meetings_add = 'meetings.add',
    meetings_edit = 'meetings.edit',
    meetings_cancel = 'meetings.cancel',
    meetings_verify = 'meetings.verify',
    meetings_sendnotification = 'meetings.sendnotification',
    meetings_execution = 'meetings.execution',
    meetings_conclusion = 'meetings.conclusion',
    meetings_calendar = 'meetings.calendar',
    license = 'license',
    standard = 'standard',
    standard_sectionfeedback = 'standard.sectionfeedback',
    standard_sectioncomment = 'standard.sectioncomment',
    standard_criterionoverview = 'standard.criterionoverview',
    standard_criterioncomment = 'standard.criterioncomment',
    standard_criterionhistory = 'standard.criterionhistory',
    standard_criterionfeedback = 'standard.criterionfeedback',
    standard_increaseexecutiontime = 'standard.increaseexecutiontime',
    standard_sendtorehearsal = 'standard.sendtorehearsal',
    standard_viewdocument = 'standard.viewdocument',
    standard_documentfeedback = 'standard.documentfeedback',
    standard_otherdepartment = 'standard.otherdepartment',
    nonstandard = 'nonstandard',
    nonstandard_view = 'nonstandard.view',
    nonstandard_addfile = 'nonstandard.addfile',
    nonstandard_edit = 'nonstandard.edit',
    nonstandard_verify = 'nonstandard.verify',
    nonstandard_accept = 'nonstandard.accept',
    announcement_sendtocorrection = 'announcement.sendtocorrection',
    nonstandard_history = 'nonstandard.history',
    nonstandart_version = 'nonstandart.version',
    nonstandard_delete = 'nonstandard.delete',
    season = 'season',
    seasons_view = 'seasons.view',
    seasons_add = 'seasons.add',
    seasons_edit = 'seasons.edit',
    seasons_delete = 'seasons.delete',
    seasons_verify = 'seasons.verify',
    seasons_conclusion = 'seasons.conclusion',
    seasons_history = 'seasons.history',
    seasons_viewcolor = 'seasons.viewcolor',
    seasons_editcolor = 'seasons.editcolor',
    seasons_viewclub = 'seasons.viewclub',
    seasons_addclub = 'seasons.addclub',
    seasons_editclub = 'seasons.editclub',
    seasons_deleteclub = 'seasons.deleteclub',
    seasons_clubhistory = 'seasons.clubhistory',
    seasons_cancellicense = 'seasons.cancellicense',
    seasons_viewsection = 'seasons.viewsection',
    seasons_addsection = 'seasons.addsection',
    seasons_editsection = 'seasons.editsection',
    seasons_sectionhistory = 'seasons.sectionhistory',
    seasons_criterionoverview = 'seasons.criterionoverview',
    seasons_addcriterion = 'seasons.addcriterion',
    seasons_editcriterion = 'seasons.editcriterion',
    seasons_deletecriterion = 'seasons.deletecriterion',
    seasons_criterionpreview = 'seasons.criterionpreview',
    seasons_verifycriterion = 'seasons.verifycriterion',
    seasons_criterionhistory = 'seasons.criterionhistory',
    seasons_viewdocument = 'seasons.viewdocument',
    seasons_adddocument = 'seasons.adddocument',
    seasons_deletedocument = 'seasons.deletedocument',
    seasons_editdocument = 'seasons.editdocument',
    seasons_documenthistory = 'seasons.documenthistory',
    template = 'template',
    templates_view = 'templates.view',
    templates_edit = 'templates.edit',
    report = 'report',
    reports_view = 'reports.view',
}
